web:
    container_name: modus_web
    image: nginx
    ports:
        - "80:80"
    volumes:
        - ./:/code
        - ./host.conf:/etc/nginx/conf.d/default.conf
    links:
        - php:php
php:
    container_name: modus_php
    build: ./
    dockerfile: ./Dockerfile
    volumes:
        - ./:/code
